version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    environment:
      TZ: Europe/Madrid

#  nodered:
#    image: nodered/node-red
#    container_name: nodered
#    ports:
#      - "1880:1880"
#    depends_on:
#      - mosquitto

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: factory
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d factory"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      # Uncomment the following lines if you need system monitoring:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /sys:/host/sys:ro
      # - /proc:/host/proc:ro
      # - /etc:/host/etc:ro
    depends_on:
      - mosquitto
      - timescaledb
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Europe/Madrid
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb

  webapp:
    build: ./webapp
    container_name: webapp
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=timescaledb
      - DATABASE_NAME=factory
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
      - SECRET_KEY=django-insecure-change-this-in-production
      - DEBUG=False
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  timescaledb_data:
  grafana_data:
